name: Auto Update M3U Playlist

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:      # This adds a "Run workflow" button for testing

permissions:
  contents: write         # Crucial: Gives the bot permission to save files

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download M3U file
        run: |
          # Replace the URL below with your actual link
          curl -L -o Kids.m3u "https://raw.githubusercontent.com/fakeall12398-sketch/JIO_TV/refs/heads/main/kids.m3u"

      - name: Check if file is empty
        run: |
          if [ ! -s kids.m3u ]; then
            echo "The downloaded file is empty. Check your URL."
            exit 1
          fi

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Kids.m3u
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Kids.m3u - $(date)"
            git push
          fi
