name: Auto Update M3U Playlist

on:
  schedule:
    # This runs every 24 hours. Adjust the cron if you need it more frequent.
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run it manually from the Actions tab

jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download M3U file
        run: |
          # Replace 'https://raw.githubusercontent.com/drmlive/fancode-live-events/refs/heads/main/fancode.m3u' with the actual link to the kids m3u
          curl -sSf "https://raw.githubusercontent.com/drmlive/fancode-live-events/refs/heads/main/fancode.m3u" > Kids.m3u

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Kids.m3u
          
          # Only commit if there are actually changes to the file
          if git diff --staged --quiet; then
            echo "No changes detected in the playlist."
          else
            git commit -m "Auto-update: kids.m3u updated at $(date)"
            git push
          fi
